#当前项目准备部署的端口
server:
  port: 8769

#注册中心
eureka:
  client:
    service-url:
      default: http://localhost:8761/eureka/

#当前项目的服务器名称
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      #/api-ribbon/**请求转发到service-ribbon服务器
      path: /api-ribbon/**
      serviceId: service-ribbon
    api-b:
      #/api-feign/**请求转发到service-feign服务器
      path: /api-feign/**
      serviceId: service-feign



